// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package i2s_reg_pkg;

  // Param list
  parameter int MaxWordWidth = 32;
  parameter int ClkDividerWidth = 16;
  parameter int WatermarkWidth = 16;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } en;
    struct packed {
      logic        q;
    } en_ws;
    struct packed {
      logic [1:0]  q;
    } en_rx;
    struct packed {
      logic        q;
    } intr_en;
    struct packed {
      logic        q;
    } en_watermark;
    struct packed {
      logic        q;
    } reset_watermark;
    struct packed {
      logic        q;
    } en_io;
    struct packed {
      logic [1:0]  q;
    } data_width;
    struct packed {
      logic        q;
    } rx_start_channel;
    struct packed {
      logic        q;
    } reset_rx_overflow;
    struct packed {
      logic        q;
    } en_tx;
    struct packed {
      logic        q;
    } reset_tx_underflow;
    struct packed {
      logic        q;
    } reset_tx_overflow;
  } i2s_reg2hw_control_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i2s_reg2hw_clkdividx_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } i2s_reg2hw_rxdata_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i2s_reg2hw_watermark_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } i2s_reg2hw_txdata_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } reset_watermark;
    struct packed {
      logic        d;
      logic        de;
    } reset_rx_overflow;
    struct packed {
      logic        d;
      logic        de;
    } reset_tx_underflow;
    struct packed {
      logic        d;
      logic        de;
    } reset_tx_overflow;
  } i2s_hw2reg_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } running;
    struct packed {
      logic        d;
    } rx_data_ready;
    struct packed {
      logic        d;
    } rx_overflow;
    struct packed {
      logic        d;
    } tx_ready;
    struct packed {
      logic        d;
    } tx_underflow;
    struct packed {
      logic        d;
    } tx_overflow;
  } i2s_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } i2s_hw2reg_rxdata_reg_t;

  typedef struct packed {
    logic [15:0] d;
  } i2s_hw2reg_waterlevel_reg_t;

  // Register -> HW type
  typedef struct packed {
    i2s_reg2hw_control_reg_t control; // [112:98]
    i2s_reg2hw_clkdividx_reg_t clkdividx; // [97:82]
    i2s_reg2hw_rxdata_reg_t rxdata; // [81:49]
    i2s_reg2hw_watermark_reg_t watermark; // [48:33]
    i2s_reg2hw_txdata_reg_t txdata; // [32:0]
  } i2s_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    i2s_hw2reg_control_reg_t control; // [61:54]
    i2s_hw2reg_status_reg_t status; // [53:48]
    i2s_hw2reg_rxdata_reg_t rxdata; // [47:16]
    i2s_hw2reg_waterlevel_reg_t waterlevel; // [15:0]
  } i2s_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] I2S_CONTROL_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] I2S_STATUS_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] I2S_CLKDIVIDX_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] I2S_RXDATA_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] I2S_WATERMARK_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] I2S_WATERLEVEL_OFFSET = 5'h 14;
  parameter logic [BlockAw-1:0] I2S_TXDATA_OFFSET = 5'h 18;

  // Reset values for hwext registers and their fields
  parameter logic [5:0] I2S_STATUS_RESVAL = 6'h 0;
  parameter logic [31:0] I2S_RXDATA_RESVAL = 32'h 0;
  parameter logic [15:0] I2S_WATERLEVEL_RESVAL = 16'h 0;

  // Register index
  typedef enum int {
    I2S_CONTROL,
    I2S_STATUS,
    I2S_CLKDIVIDX,
    I2S_RXDATA,
    I2S_WATERMARK,
    I2S_WATERLEVEL,
    I2S_TXDATA
  } i2s_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] I2S_PERMIT [7] = '{
    4'b 0011, // index[0] I2S_CONTROL
    4'b 0001, // index[1] I2S_STATUS
    4'b 0011, // index[2] I2S_CLKDIVIDX
    4'b 1111, // index[3] I2S_RXDATA
    4'b 0011, // index[4] I2S_WATERMARK
    4'b 0011, // index[5] I2S_WATERLEVEL
    4'b 1111  // index[6] I2S_TXDATA
  };

endpackage

